### ISSUE TITLE
Glitches using bold, forced line breaks and customs icons

### ISSUE THREAD

**Issue by midmidori** [OkamiWong/obsidian-custom-state-for-task-list#2]
Hello Okami, thanks a lot for making this plugin, I was looking for something like this for a while.
However I'm encountering several issues : 
- If I apply bold format to text in the same list item, whether it's markdown or HTML it'll make the text doubled;
- Same happens when I remove any bold format and do a forced line break;
- Custom icons either don't save, either save but then go back to the first custom one I've made;
- If I remove one custom icon from the list, it'll delete every single custom one at once.

Hope I'm in the right place to share, first time using GitHub as a signed in user and English isn't my first language so my apologizes if this is not described clearly enough or grammatically correct.

Cheers

**Comment by OkamiWong** [comment]
Hi there! Thanks for the feedback! I'll take a look shortly after.

_Github Issues_ is the right place to report feedbacks. No worries!

**Comment by OkamiWong** [comment]
Hi @midmidori !
I just released 1.0.2 which contains possible fixes for the issues you mentioned.

For 
> If I apply bold format to text in the same list item, whether it's markdown or HTML it'll make the text doubled;
Same happens when I remove any bold format and do a forced line break;

I tested the following markdown file and it looks alright.

<img width="244" alt="image" src="https://github.com/OkamiWong/obsidian-custom-state-for-task-list/assets/24769875/a1dd6fc3-15f7-4a42-bedd-39c0958bbae5">

<img width="244" alt="image" src="https://github.com/OkamiWong/obsidian-custom-state-for-task-list/assets/24769875/5812897a-b8e6-4322-9be2-e69a44bb43c2">

For 
> Custom icons either don't save, either save but then go back to the first custom one I've made;
If I remove one custom icon from the list, it'll delete every single custom one at once.

They should be fixed as well.

Let me know if any issue persists or new issue occurs! Thanks
